### ISSUE TITLE
Selected color not highlighted in entry page

### ISSUE THREAD

**Issue by arlingga** [percipioglobal/craft-colour-swatches#72]
Hi guys, this is a great and helpful plugin, thank you for making it real!

We are currently running on Craft CMS 3.7.18 and Craft Colour Swatches 1.4.2. It is working great, however when we select a color in the entry page, the selected color seems like losing its focus. The selected ring/shadow around the color is missing.

<img width="483" alt="Screenshot 2021-11-09 at 11 14 17" src="https://user-images.githubusercontent.com/1292039/140861482-3449c2af-0939-4686-9a17-9fe13151eeeb.png">

**Comment by arlingga** [comment]
Sorry guys, turns out it was nothing to do with the plugins, it was Craft CMS issue and already resolved by Craft CMS 3.7.18.1. Can close this one. Cheers!

**Comment by mtnorthrop** [comment]
Would it be possible to re-open this issue? The bug described here actually still exists as of Craft CMS 3.7.20.

The problem is this code in Craft's stylesheets (src/web/assets/cp/src/css/_cp.scss):
```scss
.reduce-focus-visibility {
  :focus:not(.focus-visible) {
    box-shadow: none;
  }

  .focus-visible {
    box-shadow: $darkFocusRing;
  }
}
```

This is setting `box-shadow: none;` at a higher specificity than Color Swatches' rule in ColourSwatches.css:
```css
.color-swatches button.active {
    box-shadow: 0 0 0 3px #F2842D;
}
```

I would suggest finding a different way of highlighting the selected option, since it seems that Craft has taken over the box-shadow property of form fields. Maybe we could use the `::after` pseudo element, or choose a different way of indicating the selected color option?
